PRJDIR ?= ../

ARTIFACT = LogService

INCLUDES += -I./ -I$(PRJDIR)../include

LIBS += -lLogLib -lIPCCore -lBaseLib -lCommunicDevice -lJsoncpp -lpthread

HINSTALL = LogServiceApi.h

include ../../common.mk
