PRJDIR ?= ../../

include ../../../config.mk

ARTIFACT = UpgradeService
INCLUDES += -I../../../include
LIBS += -lLogLib -lCommunicDevice -lBaseLib -lJsoncpp  -lIPCCore -lCommunicDevice
HINSTALL = UpgradeInterface.h

include ../../../common.mk



