PRJDIR ?= ../

ARTIFACT = demo

INCLUDES += -I./ -I$(PRJDIR)../include

LIBS += -lCamerasSdk -lLogLib -lBaseLib -lIPCCore -lpps -lCommunicDevice -lcapture -lscreen -lWmLib

HINSTALL =# MsgIviInterface.h

include ../../common.mk
